---
vagrant_hostname: local.cloudvm.com
vagrant_ip: 192.168.4.40

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - {
    local_path: ~/Sites/drupal,
    destination: /drupal,
    id: drupal
  }

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Other variables here.
apache_vhosts:
  - {
    servername: "local.cloudvm.com",
    documentroot: "/drupal"
  }
