---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.cloudvm.com
vagrant_ip: 192.168.4.40

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - {
    local_path: ~/Sites/drupal,
    destination: /drupal,
    excluded_paths: [".git/"],
    id: drupal
  }

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
drush_version: "6.2.0"

apache_listen_port: 8080
apache_vhosts:
  - {
    servername: "local.cloudvm.com",
    documentroot: "/drupal"
  }

php_memory_limit: "256M"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0

mysql_root_password: root
