---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Add ondrej repository for PHP 5.4.
      apt_repository: repo='ppa:ondrej/php5-oldstable'
      when: php_version == "5.4"

    - name: Add ondrej repository for PHP 5.5.
      apt_repository: repo='ppa:ondrej/php5'
      when: php_version == "5.5"

  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.varnish
    - geerlingguy.memcached
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - geerlingguy.php-xdebug
    - geerlingguy.php-xhprof
    - geerlingguy.phpmyadmin
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - name: Ensure networking tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - curl
        - wget
        - iftop
        - traceroute
        - tcpdump

    - name: Ensure performance analysis tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - htop
        - iotop
        - sysstat # includes netstat
        - lsof
        - strace

    - name: Ensure development tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - vim
        - emacs
