---
- hosts: all

  vars_files:
    - config.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.varnish
    - geerlingguy.memcached
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - geerlingguy.php-xdebug
    # - geerlingguy.phpmyadmin
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - name: Ensure networking tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - curl
        - wget
        - iftop
        - traceroute
        - tcpdump

    - name: Ensure performance analysis tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - htop
        - iotop
        - sysstat # includes netstat
        - lsof
        - strace

    - name: Ensure development tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - vim
        - emacs
