---
- hosts: all

  vars_files:
    - config.yml

  roles:
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.varnish
    - geerlingguy.memcached
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    # - geerlingguy.php-xdebug
    # - geerlingguy.phpmyadmin
    - geerlingguy.composer
    - geerlingguy.drush
